#!/usr/bin/env node
var debug = require('debug')('sportscafe:server');
var server = require('../server');

var socketer = require('../lib/socket');

server.set('port', process.env.PORT || 3000);

var serverInstance = server.listen(server.get('port'), function() {
  debug('Express server listening on port ' + serverInstance.address().port);
});

socketer.boot(serverInstance);